# OrangeFox build variables
# <https://gitlab.com/OrangeFox/vendor/recovery/-/blob/fox_12.1/orangefox_build_vars.txt>
#
# Target branch: fox_12.1

# General
FOX_TARGET_DEVICES="veux,peux"
FOX_DISABLE_UPDATEZIP=1
OF_MAINTAINER="github.com/cachiusa"
FOX_MAINTAINER_PATCH_VERSION=$(date +"%Y%m%d")

# A/B
FOX_AB_DEVICE=1
FOX_VIRTUAL_AB_DEVICE=1

# Add-ons
FOX_ASH_IS_BASH=1
FOX_DELETE_AROMAFM=1
FOX_ENABLE_APP_MANAGER=1
FOX_EXCLUDE_ZIP=1
FOX_USE_LZ4_BINARY=1
FOX_USE_NANO_EDITOR=1
FOX_USE_SED_BINARY=1
FOX_USE_TAR_BINARY=1
FOX_USE_XZ_UTILS=1
FOX_USE_ZSTD_BINARY=1
OF_ENABLE_ALL_PARTITION_TOOLS=1
OF_ENABLE_LPTOOLS=1

# Backup
OF_QUICK_BACKUP_LIST="/boot;/vendor_boot;/dtbo;"

# Filesystem
OF_BIND_MOUNT_SDCARD_ON_FORMAT=1
OF_DISPLAY_FORMAT_FILESYSTEMS_DEBUG_INFO=1
OF_UNBIND_SDCARD_F2FS=1
OF_UNMOUNT_SDCARDS_BEFORE_REBOOT=1
OF_WIPE_METADATA_AFTER_DATAFORMAT=1

# Hide unavailable settings
OF_ALLOW_DISABLE_NAVBAR=0
OF_FLASHLIGHT_ENABLE=0
OF_USE_GREEN_LED=0

# Log
OF_DONT_KEEP_LOG_HISTORY=1

# UI

## Display
OF_SCREEN_H=2400
OF_HIDE_NOTCH=1

## Install options
OF_OPTIONS_LIST_NUM=8

## Status bar
OF_CLOCK_POS=1
OF_STATUS_H=104
OF_STATUS_INDENT_LEFT=64
OF_STATUS_INDENT_RIGHT=64

# end of UI

# vendor_boot
FOX_VARIANT="vendor_boot"
FOX_VENDOR_BOOT_RECOVERY=1
FOX_INSTALLER_VENDOR_BOOT_RAMDISK_INSTALL=1

if [[ -n "$TWRP_BUILD_BOOT_IMAGE" ]]; then
FOX_VARIANT="boot"
unset FOX_VENDOR_BOOT_RECOVERY
fi
